### ISSUE TITLE
Node 16 EOL warnings in GitHub Actions

### ISSUE THREAD

**Issue by samuelhwilliams** [moergo-sc/glove80-zmk-config#10]
Hey 👋 Just copied this template to start building out my own keymap and noticed the first GitHub Actions run spat out [some warnings for Node 16 actions being deprecated](https://github.com/samuelhwilliams/glove80-zmk-config/actions/runs/8033580135) and recommending moving to Node 20 actions.

[Small patch on my copy](https://github.com/samuelhwilliams/glove80-zmk-config/commit/7f8522f615d133c31b2359b021a2494725036c0d) resolves the warnings and seems to work just fine. Might be nice to reproduce on your end so that people copying it fresh don't get those warnings.

**Comment by chrisandreae** [comment]
Thanks, applied the patch!
