### ISSUE TITLE
Build the firmware locally

### ISSUE THREAD

**Issue by GaetanLepage** [moergo-sc/glove80-zmk-config#2]
I noticed that you are using nix to build the keyboard firmware.
I tried to replicate what the github CI does locally and it seems to work fine.
I cannot test it on the keyboard because I have not yet received it.

What I did:
```sh
git clone https://github.com/moergo-sc/glove80-zmk-config.git
cd glove80-zmk-config
git clone https://github.com/moergo-sc/zmk src
nix-build config -o combined
```

This has properly generated `combined/glove80.uf2`.

My question is the following: is there any problem with doing this locally instead of relying on GitHub ?
I can't think of any reason why it wouldn't work.

**Comment by chrisandreae** [comment]
None at all: you're free to build the firmware locally and use it with your keyboard, using either Nix or with the ZMK-native West build process.

**Comment by GaetanLepage** [comment]
> None at all: you're free to build the firmware locally and use it with your keyboard, using either Nix or with the ZMK-native West build process.

Ok great !

For anyone interested, I forked this repo and embedded everything in a flake:
https://github.com/GaetanLepage/glove80-zmk-config/blob/a199811fffa66833d653c75bf31f8469b093159a/flake.nix
