### ISSUE TITLE
cachix error

### ISSUE THREAD

**Issue by dohn-joh** [moergo-sc/glove80-zmk-config#5]
I think there may be an issue with cachix-actions. I am seeing this error when trying to build.

![asdf](https://user-images.githubusercontent.com/105397306/231313693-699ee8c7-a698-4fd1-828b-0b9fbb1c00d4.png)

**Comment by prewk** [comment]
My PR solves it, you can just bump the `cachix/install-nix-action` version to 20 in `.github/workflows/build.yml`

**Comment by dohn-joh** [comment]
Thanks! This https://github.com/prewk/glove80-zmk-config/commit/3719f017f78280a2a92293f68b8eafa8a8ec1759 did the trick.
